[package]
name = "signal-tui"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
anyhow = "1.0.79"
crossterm = "0.28.1"
ratatui = "0.29.0"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
toml = "0.8.20"
